# Generated by Django 4.2.5 on 2024-05-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prompt_text', models.TextField()),
            ],
        ),
    ]
