# Generated by Django 4.2.5 on 2024-05-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sso', '0002_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='created_at',
            new_name='date_submitted',
        ),
        migrations.AddField(
            model_name='essay',
            name='content_related',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='spelling_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
