# Generated by Django 4.2.5 on 2024-06-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sso', '0004_alter_essay_content_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content_related',
            field=models.TextField(blank=True, null=True),
        ),
    ]
